config/routes.rb
Mundo::Application.routes.draw do

  resources :charts do
    collection do
      post 'line_labels'
    end
  end

  root to: "sessions#new"
  post "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  get "/logout", to: "sessions#destroy", :as => "logout"
  get "/login", to: "sessions#new", :as => "login"

  resources :identities

  resources :workouts

  resources :users

end

app/models/workout.rb
class Workout
  include Mongoid::Document
  include Mongoid::Timestamps
  Mongoid::Attributes::Dynamic

	belongs_to :user

  field :username, type: String
  field :sport, type: Integer
  field :distance_km, type: Float
  field :start_time, type: DateTime
  field :duration_sec, type: Integer
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @params = workout_params
    @workout = Workout.new(@params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render action: 'show', status: :created, location: @workout }
      else
        format.html { render action: 'new' }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:username, :sport, :distance_km, :start_time, :duration_sec)
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :sport %><br>
    <%= f.text_field :sport %>
  </div>
  <div class="field">
    <%= f.label :distance_km %><br>
    <%= f.number_field :distance_km, :step => "any" %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :duration_sec %><br>
    <%= f.number_field :duration_sec %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<h1>Listing workouts</h1>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Sport (Endomondo ID)</th>
      <th>Start time</th>
      <th>Duration</th>
      <th>Distance (km)</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= workout['username'] %></td>
        <td><%= workout['sport'] %></td>
        <td><%= workout['start_time'] %></td>
        <%= @time = workout['duration_sec'];
            @hours = @time/3600;
            @minutes = @time/60 - @hours * 60;
            @seconds = @time - (@minutes * 60 + @hours * 3600); %>
        <td><%= '%.2d:%.2d:%.2d' % [@hours, @minutes, @seconds] %></td>
        <td><%= workout['distance_km'] %></td>
        <td><%= link_to 'Show', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout', new_workout_path %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @workout.username %>
</p>

<p>
  <strong>Sport:</strong>
  <%= @workout.sport %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @workout.distance_km %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @workout.start_time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @workout.duration_sec %>
</p>

<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>