config/routes.rb
Mundo::Application.routes.draw do

  resources :charts do
    collection do
      post 'line_labels'
    end
  end

  root to: "sessions#new"
  post "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  get "/logout", to: "sessions#destroy", :as => "logout"
  get "/login", to: "sessions#new", :as => "login"

  resources :identities

  resources :workouts

  resources :users

end

app/models/identity.rb
class Identity
  include Mongoid::Document
  include OmniAuth::Identity::Models::Mongoid

  field :email, type: String
  field :name, type: String
  field :password_digest, type: String
  field :endomondo_password, type: String

  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  before_action :set_identity, only: [:show, :edit, :destroy]

  def index
    @identities = Identity.all
  end

  def show
  end

  def new
    @identity = env['omniauth.identity']
  end

  def edit
  end

  def destroy
    @identity.destroy
    respond_to do |format|
      format.html { redirect_to identities_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_identity
    @identity = Identity.find(params[:id])
  end
end

app/views/identities/_form.html.erb
<%= form_for(@identity) do |f| %>
  <% if @identity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @identity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, :placeholder => "************" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/identities/edit.html.erb
<h1>Editing identity</h1>

<%= render 'form' %>

<%= link_to 'Show', @identity %> |
<%= link_to 'Back', identities_path %>

app/views/identities/index.html.erb
<h1>Listing identities</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @identities.each do |ident| %>
    <tr>
      <td><%= ident.name %></td>
      <td><%= ident.email %></td>
      <td><%= ident.password_digest %><td>
      <td><%= link_to 'Show', ident %></td>
      <td><%= link_to 'Edit', edit_identity_path(ident) %></td>
      <td><%= link_to 'Destroy', ident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/identities/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h1>New Account</h1>

      <%= form_tag "/auth/identity/register", class: "form-horizontal" do %>
        <% if @identity && @identity.errors.any? %>
          <div class="error_messages">
            <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this account from being saved:</h2>
            <ul>
            <% @identity.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= label_tag "Username" %><br>
          <%= text_field_tag :name, @identity.try(:name), :placeholder => "Bob", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= label_tag "E-mail (the same as you use for endomondo)" %><br>
          <%= text_field_tag :email, @identity.try(:email), :placeholder => "bob@mail.com", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= label_tag :password %><br>
          <%= password_field_tag :password, "", :placeholder => "****", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= label_tag :password_confirmation %><br>
          <%= password_field_tag :password_confirmation, "", :placeholder => "****", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= label_tag :endomondo_password %><br>
          <%= password_field_tag :endomondo_password, @identity.try(:endomondo_password), :placeholder => "****", class: "form-control" %>
        </div>
        <div class="actions"><%= submit_tag "Register", class: "form-control btn-primary" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/identities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @identity.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @identity.email %>
</p>

<p>
  <strong>Password_digest:</strong>
  <%= @identity.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>